/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
And imbued with life by: wawa-lipsync logic
*/

import * as THREE from 'three'
import React, { useEffect, useMemo, useRef } from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import type { GLTF } from 'three-stdlib'
import { useControls } from 'leva'
import { Lipsync } from 'wawa-lipsync'

type GLTFResult = GLTF & {
  nodes: {
    Wolf3D_Hair: THREE.SkinnedMesh
    Wolf3D_Outfit_Top: THREE.SkinnedMesh
    Wolf3D_Outfit_Bottom: THREE.SkinnedMesh
    Wolf3D_Outfit_Footwear: THREE.SkinnedMesh
    Wolf3D_Body: THREE.SkinnedMesh
    EyeLeft: THREE.SkinnedMesh
    EyeRight: THREE.SkinnedMesh
    Wolf3D_Head: THREE.SkinnedMesh
    Wolf3D_Teeth: THREE.SkinnedMesh
    Hips: THREE.Bone
  }
  materials: {
    Wolf3D_Hair: THREE.MeshStandardMaterial
    Wolf3D_Outfit_Top: THREE.MeshStandardMaterial
    Wolf3D_Outfit_Bottom: THREE.MeshStandardMaterial
    Wolf3D_Outfit_Footwear: THREE.MeshStandardMaterial
    Wolf3D_Body: THREE.MeshStandardMaterial
    Wolf3D_Eye: THREE.MeshStandardMaterial
    Wolf3D_Skin: THREE.MeshStandardMaterial
    Wolf3D_Teeth: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Ziva(props: React.ComponentProps<'group'>) {
  const { scene } = useGLTF('/models/Ziva.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult

  // 1. Initialize the Lipsync instance
  const lipsync = useMemo(() => new Lipsync(), [])
  const audioRef = useRef<HTMLAudioElement | null>(null)

  // 3. Setup Audio on mount
  useEffect(() => {
    const newAudio = new Audio('/audio/intro.mp3') // Ensure this file exists in /public/audio/
    newAudio.loop = false
    audioRef.current = newAudio
    
    // Connect audio to lipsync analyzer
    lipsync.connectAudio(newAudio)

    return () => {
        newAudio.pause()
    }
  }, [lipsync])

  // 2. UI Controls for testing
  useControls({
    playAudio: {
      value: false,
      onChange: (v: boolean) => {
        const audio = audioRef.current
        if (!audio) {
          console.warn('Audio not loaded yet')
          return
        }
        if (v) {
          audio.play().catch(err => console.error('Error playing audio:', err))
        } else {
          audio.pause()
        }
      },
    },
  })

  // 4. The Animation Loop
  useFrame(() => {
    const head = nodes.Wolf3D_Head
    const teeth = nodes.Wolf3D_Teeth

    if (!head || !lipsync) return

    // Run the analysis for the current frame
    lipsync.processAudio()
    const currentViseme = lipsync.viseme // e.g., "aa", "E", "sil"

    // Smoothly reset all morph targets to 0
    // This ensures we don't get "stuck" with an open mouth
    Object.keys(head.morphTargetDictionary!).forEach((key) => {
      if (key.startsWith('viseme_')) {
        const targetIndex = head.morphTargetDictionary![key]
        const teethIndex = teeth.morphTargetDictionary![key]

        // Determine target value: 1 if it matches current viseme, 0 otherwise
        // We map "aa" -> "viseme_aa"
        const isCurrent = key === `viseme_${currentViseme}` ? 1 : 0
        
        // Lerp (Linear Interpolate) for smooth transition
        // 0.2 is the speed factor (adjust for snappiness)
        head.morphTargetInfluences![targetIndex] = THREE.MathUtils.lerp(
          head.morphTargetInfluences![targetIndex],
          isCurrent,
          0.2
        )
        
        if (teethIndex !== undefined) {
          teeth.morphTargetInfluences![teethIndex] = THREE.MathUtils.lerp(
            teeth.morphTargetInfluences![teethIndex],
            isCurrent,
            0.2
          )
        }
      }
    })
  })

  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
      <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
      <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
    </group>
  )
}

useGLTF.preload('/models/Ziva.glb')