/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Fixed: Added safety checks for Animations
*/

import * as THREE from 'three'
import React, { useEffect, useMemo, useRef, useState } from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { type GLTF, SkeletonUtils } from 'three-stdlib'
import { useControls } from 'leva'
import { Lipsync } from 'wawa-lipsync'

type GLTFResult = GLTF & {
  nodes: {
    Wolf3D_Hair: THREE.SkinnedMesh
    Wolf3D_Outfit_Top: THREE.SkinnedMesh
    Wolf3D_Outfit_Bottom: THREE.SkinnedMesh
    Wolf3D_Outfit_Footwear: THREE.SkinnedMesh
    Wolf3D_Body: THREE.SkinnedMesh
    EyeLeft: THREE.SkinnedMesh
    EyeRight: THREE.SkinnedMesh
    Wolf3D_Head: THREE.SkinnedMesh
    Wolf3D_Teeth: THREE.SkinnedMesh
    Hips: THREE.Bone
  }
  materials: {
    Wolf3D_Hair: THREE.MeshStandardMaterial
    Wolf3D_Outfit_Top: THREE.MeshStandardMaterial
    Wolf3D_Outfit_Bottom: THREE.MeshStandardMaterial
    Wolf3D_Outfit_Footwear: THREE.MeshStandardMaterial
    Wolf3D_Body: THREE.MeshStandardMaterial
    Wolf3D_Eye: THREE.MeshStandardMaterial
    Wolf3D_Skin: THREE.MeshStandardMaterial
    Wolf3D_Teeth: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Ziva(props: React.ComponentProps<'group'>) {
  const group = useRef<THREE.Group>(null)
  const { scene } = useGLTF('/models/Ziva.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult

  // --- Animation Logic ---
  const { animations: clips } = useGLTF('/models/Animations.glb')
  
  // FIX: Added safety check (clips && clips.forEach)
  useMemo(() => {
    if (clips) {
      clips.forEach((clip) => {
        if (clip.tracks) {
             clip.tracks.forEach((track) => {
              // Remove the "mixamorig" prefix if present
              track.name = track.name.replace('mixamorig', '')
            })
        }
      })
    }
  }, [clips])

  const { actions, names } = useAnimations(clips || [], group) // Pass empty array if clips is null

  const { animation } = useControls({
    animation: { value: names[0] || "", options: names },
  })

  useEffect(() => {
    // Safety check: if no animation selected or actions not ready
    if (!animation || !actions[animation]) return

    const action = actions[animation]
    
    action
      .reset()
      .fadeIn(0.5)
      .play()

    return () => {
      action?.fadeOut(0.5)
    }
  }, [animation, actions])

  // --- Lipsync Logic ---
  const lipsync = useMemo(() => new Lipsync(), [])
  const [audio, setAudio] = useState<HTMLAudioElement | null>(null)

  useControls({
    playAudio: {
      value: false,
      onChange: (v) => {
        if (!audio) return
        v ? audio.play() : audio.pause()
      },
    },
  })

  useEffect(() => {
    const newAudio = new Audio('/audio/intro.mp3')
    newAudio.loop = false
    setAudio(newAudio)
    lipsync.connectAudio(newAudio)

    return () => {
        newAudio.pause()
    }
  }, [lipsync])

  useFrame(() => {
    const head = nodes.Wolf3D_Head
    const teeth = nodes.Wolf3D_Teeth

    if (!head || !lipsync || !audio || audio.paused) return

    lipsync.processAudio()
    const currentViseme = lipsync.viseme 

    Object.keys(head.morphTargetDictionary!).forEach((key) => {
      if (key.startsWith('viseme_')) {
        const targetIndex = head.morphTargetDictionary![key]
        const teethIndex = teeth.morphTargetDictionary![key]
        const isCurrent = key === `viseme_${currentViseme}` ? 1 : 0
        
        head.morphTargetInfluences![targetIndex] = THREE.MathUtils.lerp(
          head.morphTargetInfluences![targetIndex],
          isCurrent,
          0.2
        )
        
        if (teethIndex !== undefined) {
          teeth.morphTargetInfluences![teethIndex] = THREE.MathUtils.lerp(
            teeth.morphTargetInfluences![teethIndex],
            isCurrent,
            0.2
          )
        }
      }
    })
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
      <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
      <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
    </group>
  )
}

useGLTF.preload('/models/Ziva.glb')
useGLTF.preload('/models/Animations.glb')